[General]

network = SatelliteNetwork

sim-time-limit = 100s

# Mobility

**.satellite[*].mobility.speed = 7000mps

# Satellite transmitter and receiver parameters

**.groundStation[*].udpApp.startTime = uniform(0s, 10s)

**.groundStation[*].udpApp.sendInterval = exponential(1s)

**.groundStation[*].udpApp.messageSize = 256B

**.groundStation[*].udpApp.localPort = 1000

**.groundStation[*].udpApp.destPort = 2000

**.satellite[*].udpApp.localPort = 2000

**.satellite[*].mobility.typename = "BonnMotionMobility"
**.satellite[*].mobility.traceFile = "./movements/line.movements"
SatelliteNetwork.radioMedium.backgroundNoise.power = 10dBm